
services:
  kong:
    image: kong
    container_name: kong
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/kong.yaml # Tell kong where to find the config in the container
    volumes:
      - ./kong.yaml:/usr/kong.yaml # Bind mount the kong.yaml from the project dir into the container path
    ports:
      - "80:8000"   
