services:  
  yin: 
    image : oldgitdocker/yin    
    build: 
      context: ./yin 
    pull_policy: always
    container_name: yin
    ports:
      - 4000:3000
    env_file:
      - .env 

  yang: 
    image: oldgitdocker/yang    
    build: 
      context: ./yang 
    pull_policy: always
    container_name: yang
    ports:
      - 4001:3001 
    env_file:
      - .env
