services:
  app1:
    build: .
    image: oldgitdocker/app1
    container_name: app1
    ports:
      - "4001:3001"
    environment:
      - APP1_PORT=3001
     # - RABBITMQ_URL=amqp://admin:admin@localhost:5672
     # - RABBITMQ_URL=amqp://admin:admin@host.docker.internal:5672
      - RABBITMQ_URL=amqp://admin:admin@10.0.1.7:5672
      - COMPONENTS_FILE=/usr/src/app/data/components.json
    volumes:
      - data:/usr/src/app/data
  #  restart: always
volumes:
  data:
