services:
  app2:
    build: .
    image: oldgitdocker/app3
    container_name: app3
    ports:
      - "4003:3003"
    environment:
      - APP3_PORT=3003
     # - RABBITMQ_URL=amqp://admin:admin@localhost:5672
     # - RABBITMQ_URL=amqp://admin:admin@host.docker.internal:5672
      - RABBITMQ_URL=amqp://admin:admin@10.0.1.7:5672
      - COMPONENTS_FILE=/usr/src/app/data/components.json
    restart: always
    volumes:
      - data:/usr/src/app/data

volumes:
  data:
