services:  
  demo1:        
    image: oldgitdocker/demo
 #   image: demo
    build: 
      context: .          # Where is the Dockerfile
    container_name: demo1 
    ports:
      - 4000:3000 

  # demo2: 
  #   image: demo  # A second image is built. Leave second build out docker build -t demo . 
  # #  build: 
  # #    context: . # Only really want one image as both containers in this example are the same
  #   container_name: demo2
  #   ports:
  #     - 4001:3000   