services:  
  yin: 
    image: oldgitdocker/yin
    pull_policy: always 
    build: 
      context: ./yin
    container_name: yin
    env_file:
    - .env
    ports:
      - ${YIN_CONT_PORT}:${YIN_PORT} 

  yang: 
    image: oldgitdocker/yang
    pull_policy: always
    build: 
      context: ./yang 
    container_name: yang
    env_file:
    - .env
    ports:
      - ${YANG_CONT_PORT}:${YANG_PORT}  
